//
//  RecommendationStore.swift
//  Recommend-It
//
//  Created by Derrick Showers on 5/5/15.
//  Copyright (c) 2015 Derrick Showers. All rights reserved.
//

import Foundation

/**
    Store for all recommendations. Keeps them in an `allRecommendations` array. Also
    includes convenience methods for getting and setting recommendations in the array.

    This should either be instantiated in the AppDelegate or passed between view 
    controllers--all classes should have access to the same instance.
*/
class RecommendationStore {
    /// MARK: - Properties
    var allRecommendations = [Recommendation]()
    
    /**
        Create a recommendation with YelpId and business name. Other properites can be
        added to the instance that is returned.
    
        - parameter yelpId: The ID generated by Yelp
        - parameter name: The name of the business
    
        - returns: A reference to the new recommendation that was added to the allRecommendations array
    */
    func createRecommendation(yelpId yelpId: String, name: String) -> Recommendation {
        let rec = Recommendation(yelpId: yelpId, name: name)
        allRecommendations.append(rec)
        return rec
    }
    
    /**
        Get a recommendation based on the name of the business. Looks through the array for the correct
        business and returns it.
    
        - parameter name: The name of the business
    
        - returns: *(optional)* A reference to the instance of the business
    */
    func getRecommendation(name name: String) -> Recommendation? {
        var recommendation: Recommendation?
        for rec in allRecommendations {
            if rec.name == name {
                recommendation = rec
            }
        }
        return recommendation
    }
}